[build]
  command = "npm run build"
  publish = "dist/learn-angular-01/browser"
  environment = { NODE_OPTIONS = "--max_old_space_size=4096", NODE_VERSION = "20.9.0", NPM_FLAGS = "--no-audit --no-fund" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
